apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: clearcut
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo
